
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 06 13:58:23 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 4;
  public static final int CONST = 26;
  public static final int CHAR = 28;
  public static final int GE = 41;
  public static final int LPAREN = 8;
  public static final int SEMI = 10;
  public static final int CONTINUE = 23;
  public static final int MINUS = 32;
  public static final int RPAREN = 9;
  public static final int AND = 45;
  public static final int LT = 42;
  public static final int OR = 44;
  public static final int BOOL = 29;
  public static final int COMMA = 11;
  public static final int CLASS = 46;
  public static final int INC = 33;
  public static final int DIV = 36;
  public static final int EXT = 47;
  public static final int PLUS = 31;
  public static final int ASSIGN = 3;
  public static final int IF = 21;
  public static final int DOT = 12;
  public static final int LE = 43;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int RBRACKET = 5;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int MUL = 35;
  public static final int MOD = 37;
  public static final int NUMBER = 27;
  public static final int BREAK = 24;
  public static final int IDENT = 30;
  public static final int VOID = 18;
  public static final int EQ = 38;
  public static final int ARROW = 14;
  public static final int FOREACH = 20;
  public static final int COLON = 13;
  public static final int LBRACE = 6;
  public static final int ELSE = 22;
  public static final int READ = 16;
  public static final int WHILE = 19;
  public static final int RBRACE = 7;
  public static final int NE = 39;
  public static final int PROG = 2;
  public static final int DEC = 34;
  public static final int GT = 40;
  public static final int PRINT = 15;
}

